#!/bin/bash

SLURM_DIR="/$REPLAY_USER/slurmR"
SLURM_REPLAY="/$REPLAY_USER/slurm-replay"
export PATH=$SLURM_DIR/bin:$SLURM_DIR/sbin:$SLURM_REPLAY/submitter:$PATH
export LD_LIBRARY_PATH=$SLURM_DIR/lib:$SLURM_REPLAY/distime
export DISTIME_SHMEMCLOCK_NAME="${DISTIME_SHMEMCLOCK_NAME}"

# Do not use srun, steps are not considered
job_runner -d <DURATION> -x <EXIT_CODE> -j <JOB_ID> -n <JOB_NODES> -r <CLOCK_RATE> -i <INIT_TIME> -p <PRESET> -e <TIME_END>
